//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.01 at 08:47:06 PM CET 
//


package prognoza;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="prognoza" maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="lokacija"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="drzava"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;simpleContent&gt;
 *                                   &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
 *                                     &lt;attribute name="iso"&gt;
 *                                       &lt;simpleType&gt;
 *                                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                                           &lt;length value="2"/&gt;
 *                                         &lt;/restriction&gt;
 *                                       &lt;/simpleType&gt;
 *                                     &lt;/attribute&gt;
 *                                   &lt;/extension&gt;
 *                                 &lt;/simpleContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                             &lt;element name="grad" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="datum"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="dan"&gt;
 *                               &lt;simpleType&gt;
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                                   &lt;enumeration value="Ponedjeljak"/&gt;
 *                                   &lt;enumeration value="Utorak"/&gt;
 *                                   &lt;enumeration value="Srijeda"/&gt;
 *                                   &lt;enumeration value="Četvrtak"/&gt;
 *                                   &lt;enumeration value="Petak"/&gt;
 *                                   &lt;enumeration value="Subota"/&gt;
 *                                   &lt;enumeration value="Nedjelja"/&gt;
 *                                 &lt;/restriction&gt;
 *                               &lt;/simpleType&gt;
 *                             &lt;/element&gt;
 *                             &lt;element name="vrijeme" type="{http://www.w3.org/2001/XMLSchema}time"/&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="temperatura"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;simpleContent&gt;
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;integer"&gt;
 *                           &lt;attribute name="jedinica" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                         &lt;/extension&gt;
 *                       &lt;/simpleContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="opis" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                 &lt;/sequence&gt;
 *                 &lt;attribute name="dohvacena" type="{http://www.w3.org/2001/XMLSchema}dateTime" /&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "prognoza"
})
@XmlRootElement(name = "prognoze")
public class Prognoze {

    protected List<Prognoze.Prognoza> prognoza;

    /**
     * Gets the value of the prognoza property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the prognoza property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPrognoza().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Prognoze.Prognoza }
     * 
     * 
     */
    public List<Prognoze.Prognoza> getPrognoza() {
        if (prognoza == null) {
            prognoza = new ArrayList<Prognoze.Prognoza>();
        }
        return this.prognoza;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="lokacija"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="drzava"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;simpleContent&gt;
     *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
     *                           &lt;attribute name="iso"&gt;
     *                             &lt;simpleType&gt;
     *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *                                 &lt;length value="2"/&gt;
     *                               &lt;/restriction&gt;
     *                             &lt;/simpleType&gt;
     *                           &lt;/attribute&gt;
     *                         &lt;/extension&gt;
     *                       &lt;/simpleContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                   &lt;element name="grad" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="datum"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="dan"&gt;
     *                     &lt;simpleType&gt;
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *                         &lt;enumeration value="Ponedjeljak"/&gt;
     *                         &lt;enumeration value="Utorak"/&gt;
     *                         &lt;enumeration value="Srijeda"/&gt;
     *                         &lt;enumeration value="Četvrtak"/&gt;
     *                         &lt;enumeration value="Petak"/&gt;
     *                         &lt;enumeration value="Subota"/&gt;
     *                         &lt;enumeration value="Nedjelja"/&gt;
     *                       &lt;/restriction&gt;
     *                     &lt;/simpleType&gt;
     *                   &lt;/element&gt;
     *                   &lt;element name="vrijeme" type="{http://www.w3.org/2001/XMLSchema}time"/&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="temperatura"&gt;
     *           &lt;complexType&gt;
     *             &lt;simpleContent&gt;
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;integer"&gt;
     *                 &lt;attribute name="jedinica" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *               &lt;/extension&gt;
     *             &lt;/simpleContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="opis" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *       &lt;/sequence&gt;
     *       &lt;attribute name="dohvacena" type="{http://www.w3.org/2001/XMLSchema}dateTime" /&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "lokacija",
        "datum",
        "temperatura",
        "opis"
    })
    public static class Prognoza {

        @XmlElement(required = true)
        protected Prognoze.Prognoza.Lokacija lokacija;
        @XmlElement(required = true)
        protected Prognoze.Prognoza.Datum datum;
        @XmlElement(required = true)
        protected Prognoze.Prognoza.Temperatura temperatura;
        @XmlElement(required = true)
        protected String opis;
        @XmlAttribute(name = "dohvacena")
        @XmlSchemaType(name = "dateTime")
        protected XMLGregorianCalendar dohvacena;

        /**
         * Gets the value of the lokacija property.
         * 
         * @return
         *     possible object is
         *     {@link Prognoze.Prognoza.Lokacija }
         *     
         */
        public Prognoze.Prognoza.Lokacija getLokacija() {
            return lokacija;
        }

        /**
         * Sets the value of the lokacija property.
         * 
         * @param value
         *     allowed object is
         *     {@link Prognoze.Prognoza.Lokacija }
         *     
         */
        public void setLokacija(Prognoze.Prognoza.Lokacija value) {
            this.lokacija = value;
        }

        /**
         * Gets the value of the datum property.
         * 
         * @return
         *     possible object is
         *     {@link Prognoze.Prognoza.Datum }
         *     
         */
        public Prognoze.Prognoza.Datum getDatum() {
            return datum;
        }

        /**
         * Sets the value of the datum property.
         * 
         * @param value
         *     allowed object is
         *     {@link Prognoze.Prognoza.Datum }
         *     
         */
        public void setDatum(Prognoze.Prognoza.Datum value) {
            this.datum = value;
        }

        /**
         * Gets the value of the temperatura property.
         * 
         * @return
         *     possible object is
         *     {@link Prognoze.Prognoza.Temperatura }
         *     
         */
        public Prognoze.Prognoza.Temperatura getTemperatura() {
            return temperatura;
        }

        /**
         * Sets the value of the temperatura property.
         * 
         * @param value
         *     allowed object is
         *     {@link Prognoze.Prognoza.Temperatura }
         *     
         */
        public void setTemperatura(Prognoze.Prognoza.Temperatura value) {
            this.temperatura = value;
        }

        /**
         * Gets the value of the opis property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOpis() {
            return opis;
        }

        /**
         * Sets the value of the opis property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOpis(String value) {
            this.opis = value;
        }

        /**
         * Gets the value of the dohvacena property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getDohvacena() {
            return dohvacena;
        }

        /**
         * Sets the value of the dohvacena property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setDohvacena(XMLGregorianCalendar value) {
            this.dohvacena = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="dan"&gt;
         *           &lt;simpleType&gt;
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
         *               &lt;enumeration value="Ponedjeljak"/&gt;
         *               &lt;enumeration value="Utorak"/&gt;
         *               &lt;enumeration value="Srijeda"/&gt;
         *               &lt;enumeration value="Četvrtak"/&gt;
         *               &lt;enumeration value="Petak"/&gt;
         *               &lt;enumeration value="Subota"/&gt;
         *               &lt;enumeration value="Nedjelja"/&gt;
         *             &lt;/restriction&gt;
         *           &lt;/simpleType&gt;
         *         &lt;/element&gt;
         *         &lt;element name="vrijeme" type="{http://www.w3.org/2001/XMLSchema}time"/&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "dan",
            "vrijeme"
        })
        public static class Datum {

            @XmlElement(required = true)
            protected String dan;
            @XmlElement(required = true)
            @XmlSchemaType(name = "time")
            protected XMLGregorianCalendar vrijeme;

            /**
             * Gets the value of the dan property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDan() {
                return dan;
            }

            /**
             * Sets the value of the dan property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDan(String value) {
                this.dan = value;
            }

            /**
             * Gets the value of the vrijeme property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getVrijeme() {
                return vrijeme;
            }

            /**
             * Sets the value of the vrijeme property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setVrijeme(XMLGregorianCalendar value) {
                this.vrijeme = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="drzava"&gt;
         *           &lt;complexType&gt;
         *             &lt;simpleContent&gt;
         *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
         *                 &lt;attribute name="iso"&gt;
         *                   &lt;simpleType&gt;
         *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
         *                       &lt;length value="2"/&gt;
         *                     &lt;/restriction&gt;
         *                   &lt;/simpleType&gt;
         *                 &lt;/attribute&gt;
         *               &lt;/extension&gt;
         *             &lt;/simpleContent&gt;
         *           &lt;/complexType&gt;
         *         &lt;/element&gt;
         *         &lt;element name="grad" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "drzava",
            "grad"
        })
        public static class Lokacija {

            @XmlElement(required = true)
            protected Prognoze.Prognoza.Lokacija.Drzava drzava;
            @XmlElement(required = true)
            protected String grad;

            /**
             * Gets the value of the drzava property.
             * 
             * @return
             *     possible object is
             *     {@link Prognoze.Prognoza.Lokacija.Drzava }
             *     
             */
            public Prognoze.Prognoza.Lokacija.Drzava getDrzava() {
                return drzava;
            }

            /**
             * Sets the value of the drzava property.
             * 
             * @param value
             *     allowed object is
             *     {@link Prognoze.Prognoza.Lokacija.Drzava }
             *     
             */
            public void setDrzava(Prognoze.Prognoza.Lokacija.Drzava value) {
                this.drzava = value;
            }

            /**
             * Gets the value of the grad property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getGrad() {
                return grad;
            }

            /**
             * Sets the value of the grad property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setGrad(String value) {
                this.grad = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType&gt;
             *   &lt;simpleContent&gt;
             *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
             *       &lt;attribute name="iso"&gt;
             *         &lt;simpleType&gt;
             *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
             *             &lt;length value="2"/&gt;
             *           &lt;/restriction&gt;
             *         &lt;/simpleType&gt;
             *       &lt;/attribute&gt;
             *     &lt;/extension&gt;
             *   &lt;/simpleContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "value"
            })
            public static class Drzava {

                @XmlValue
                protected String value;
                @XmlAttribute(name = "iso")
                protected String iso;

                /**
                 * Gets the value of the value property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getValue() {
                    return value;
                }

                /**
                 * Sets the value of the value property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setValue(String value) {
                    this.value = value;
                }

                /**
                 * Gets the value of the iso property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getIso() {
                    return iso;
                }

                /**
                 * Sets the value of the iso property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setIso(String value) {
                    this.iso = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;simpleContent&gt;
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;integer"&gt;
         *       &lt;attribute name="jedinica" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *     &lt;/extension&gt;
         *   &lt;/simpleContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class Temperatura {

            @XmlValue
            protected BigInteger value;
            @XmlAttribute(name = "jedinica")
            protected String jedinica;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setValue(BigInteger value) {
                this.value = value;
            }

            /**
             * Gets the value of the jedinica property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getJedinica() {
                return jedinica;
            }

            /**
             * Sets the value of the jedinica property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setJedinica(String value) {
                this.jedinica = value;
            }

        }

    }

}
